name: Daily Commit

on:
  schedule:
    - cron: '40 23 * * *'  # Runs daily at 23:40 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Change
        run: echo "$(date)" > daily_update.txt

      - name: Commit and Push (your-email@example.com)
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "24ds1000121@ds.study.iitm.ac.in"
          git add daily_update.txt
          git commit -m "Daily update: $(date)"
          git push
